In [2]:
import numpy as np

# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
print(arr)

# Printing type of arr object
print("Array is of type: ", type(arr))

# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

# Printing shape of array
print("Shape of array: ", arr.shape)

# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

[[1 2 3]
 [4 2 5]]
Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


In [3]:
import numpy as np
# create a 2D array
array1 = np.array([[1, 3], [5, 7]])
# calculate the mean of the entire array
result1 = np.mean(array1)
print("Entire Array:",result1)  # 4.0


Entire Array: 4.0


In [4]:
# calculate the mean along vertical axis (axis=0)
result2 = np.mean(array1, axis=0)
print("Along Vertical Axis:",result2)  # [3. 5.]

# calculate the mean along  horizontal axis (axis=1)
result3 = np.mean(array1, axis=1)
print("Along Horizontal Axis :",result3)  # [2. 6.]


Along Vertical Axis: [3. 5.]
Along Horizontal Axis : [2. 6.]


In [1]:
# Reshaping 3X4 array to 2X2X3 array

import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])

newarr = arr.reshape(2,2,3)

print ("Original array:\n", arr)
print("---------------")
print ("Reshaped array:\n", newarr)

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
---------------
Reshaped array:
 [[1 2 3 4 5 2]
 [4 2 1 2 0 1]]


In [13]:
# Using -1 to infer a dimension
# Reshaping the array into a 2D array
# '-1' allows to calculate the number of rows based on the total number of 
#elements
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = np.reshape(arr, (-1, 2))  
print(reshaped_arr)
''' order : [C-contiguous, F-contiguous, A-contiguous; optional]

    'C' (default): Row-major order.
    'F': Column-major order.
    'A': Fortran-like index order if the array is Fortran-contiguous; otherwise, C-like order.
    'K': Keeps the array's order as close to its original as possible.'''
# Reshaping the array into a 2D array with 2 rows and 3 columns 
# with column-major order
reshaped_arr = np.reshape(arr, (2, 3), order='F')
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [3]:
# Flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flat_arr = arr.flatten()

print ("Original array:\n", arr)
print ("Fattened array:\n", flat_arr)

Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


In [ ]:
'''
In the Python pandas library, Series and DataFrame are the two fundamental 
data structures used for data manipulation and analysis.
Pandas is a popular open-source data manipulation and analysis library for 
Python. It provides easy-to-use data structures like DataFrame and Series, 
which are designed to make working with structured data fast, easy, and 
expressive. Pandas are widely used in data science, machine learning, and 
data analysis for tasks such as data cleaning, transformation, and 
exploration.'''



In [1]:
''' A DataFrame is a two-dimensional labeled data structure with columns of 
potentially different types. It can be thought of as a table or a spreadsheet,
consisting of rows and columns. Each column in a DataFrame is a Series 
object, sharing a common index for the rows.
DataFrames are highly versatile and are the primary structure for working 
with tabular data in pandas.'''
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 32, 18, 47, 33],
    'City': ['New York', 'Paris', 'London', 'Tokyo', 'Sydney']
}
df = pd.DataFrame(data)


In [2]:
df

Name  Age      City
0    Alice   25  New York
1      Bob   32     Paris
2  Charlie   18    London
3    David   47     Tokyo
4      Eve   33    Sydney

In [3]:
# access a single row
single_row = df.loc[2]
print("Single row:", single_row)
print()

# access rows 0, 3 and 4
row_list = df.loc[[0, 3, 4]]
print("List of Rows:", row_list)
print()


# access a list of columns
column_list = df.loc[:, ['Name', 'Age']]
print("List of Columns:", column_list)
print()


# access second row of 'Name' column
specific_value = df.loc[1, 'Name']
print("Specific Value:", specific_value)


Single row: Name    Charlie
Age          18
City     London
Name: 2, dtype: object

List of Rows:     Name  Age      City
0  Alice   25  New York
3  David   47     Tokyo
4    Eve   33    Sydney

List of Columns:       Name  Age
0    Alice   25
1      Bob   32
2  Charlie   18
3    David   47
4      Eve   33

Specific Value: Bob


In [4]:
"""In the Python Pandas library, .iloc[] is an indexer used for integer-location-based indexing of 
data in a DataFrame. It allows users to select specific rows and columns by providing integer indices,
making it a valuable tool for data manipulation and extraction based on numerical positions within the
DataFrame. This indexer is particularly useful when you want to access or manipulate data using 
integer-based positional indexing rather than labels."""
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 32, 18, 47, 33],
    'City': ['New York', 'Paris', 'London', 'Tokyo', 'Sydney']
}
df = pd.DataFrame(data)
df.iloc[:, 0:2]



Name  Age
0    Alice   25
1      Bob   32
2  Charlie   18
3    David   47
4      Eve   33

In [5]:
df.iloc[0:2, 1:3]

Age      City
0   25  New York
1   32     Paris

In [6]:
# Adding columns using assign() method
import pandas as pd
data= {'Name': ['John', 'Henry', 'Jack', 'Mary'],
      'Age':[23, 34, 25, 27], 
      "Address":['Bengaluru', 'Hubli', 'Hydrabad', 'Pune']}
#creating data frames using dictionary
dfd=pd.DataFrame(data)
dfd
# using assign() method to add columns
df2=dfd.assign(Height=[5.9, 5.6, 5.8])
df2

ValueError: Length of values (3) does not match length of index (4)

In [6]:
#Using insert() method to add columns to data frame at specified position
dfd.insert(1, "Address",['Bengaluru', 'Hubli', 'Hydrabad', 'Pune'], 
           allow_duplicates=True)
#displaying the output
dfd
#df3={"Name":'Tom', 'Age':35, 'Address':'Bengaluru', 'Height':5.7}
#df4=df2.append(df3, ignore_index=True)
#df4

Address    Address   Name    Address    Address  Age    Address
0  Bengaluru  Bengaluru   John  Bengaluru  Bengaluru   23  Bengaluru
1      Hubli      Hubli  Henry      Hubli      Hubli   34      Hubli
2   Hydrabad   Hydrabad   Jack   Hydrabad   Hydrabad   25   Hydrabad
3       Pune       Pune   Mary       Pune       Pune   27       Pune

In [12]:
#Adding Rows Using Concat()
#create the first data frame
import pandas as pd
data= {'Name': ['John', 'Henry', 'Jack', 'Mary'],
      'Age':[23, 34, 25, 27], 
      "Address":['Bengaluru', 'Hubli', 'Hydrabad', 'Pune']}
df1=pd.DataFrame(data)

#create the second data frame
data1= {'Name': ['Jimmy', 'Herry'],
      'Age':[33, 34], 
      "Qualification":['MCA', 'BE']}
df2=pd.DataFrame(data1)

df3=pd.concat([df1,df2], axis=1)
df3


Name  Age    Address   Name   Age Qualification
0   John   23  Bengaluru  Jimmy  33.0           MCA
1  Henry   34      Hubli  Herry  34.0            BE
2   Jack   25   Hydrabad    NaN   NaN           NaN
3   Mary   27       Pune    NaN   NaN           NaN

In [26]:
df4=pd.concat([df1,df2], axis=0)
df4

Name  Age    Address Qualification
0   John   23  Bengaluru           NaN
1  Henry   34      Hubli           NaN
2   Jack   25   Hydrabad           NaN
3   Mary   27       Pune           NaN
0  Jimmy   33        NaN           MCA
1  Herry   34        NaN            BE

In [27]:
#droping by column names
df4.drop(["Address", "Qualification"])


Name  Age
0   John   23
1  Henry   34
2   Jack   25
3   Mary   27
0  Jimmy   33
1  Herry   34

In [28]:
df4


Name  Age    Address Qualification
0   John   23  Bengaluru           NaN
1  Henry   34      Hubli           NaN
2   Jack   25   Hydrabad           NaN
3   Mary   27       Pune           NaN
0  Jimmy   33        NaN           MCA
1  Herry   34        NaN            BE

In [29]:
df5=df4.drop(["Address", "Qualification"], axis=1)
df4

Name  Age
0   John   23
1  Henry   34
2   Jack   25
3   Mary   27
0  Jimmy   33
1  Herry   34

In [31]:
#droping rows by index label
import pandas as pd
data= {'Name': ['John', 'Henry', 'Jack', 'Mary'],
      'Age':[23, 34, 25, 27], 
      "Address":['Bengaluru', 'Hubli', 'Hydrabad', 'Pune']}
df1=pd.DataFrame(data)
# Setting the index to 'Name'
df1.set_index('Name', inplace=True)
# dropping the rows mentioned
df1.drop(['Henry'], inplace=True)
df1

Age    Address
Name                
John   23  Bengaluru
Jack   25   Hydrabad
Mary   27       Pune

In [33]:
# Sorting the Data farme, here na_position= 'last' moves 
#the rows contatining the NA values to the last and sort the remaining rows
df1.sort_values("Name", axis=0, inplace=True, ascending = False, na_position='last');
df1

Age    Address
Name                
Mary   27       Pune
John   23  Bengaluru
Jack   25   Hydrabad

In [43]:
#Grouping the data
# groupby() method can be used. Python allows to compute aggreagations such as sum(), mean(), median()
#min(), max() on the gropued data
import pandas as pd
data= {'Name': ['John', 'Henry', 'Jack', 'Mary', 'Mary', 'Joseph'],
      'Age':[23, 34, 25, 27, 32, 40], 
      'Address':['Bengaluru', 'Hubli', 'Hydrabad', 'Pune', 'Bengaluru', 'Pune'],
      'Salary': [25000, 32000, 56000, 100000, 45000, 120000]}
df1=pd.DataFrame(data)
#calculating the mean salary grouped by address
age_group=df1['Age'].groupby(df1['Address'])

print(age_group.mean())


Address
Bengaluru    27.5
Hubli        34.0
Hydrabad     25.0
Pune         33.5
Name: Age, dtype: float64


In [ ]:
'''
Pandas Series:

    A Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floats, Python objects, etc.).
    It is essentially a single column of data, similar to a NumPy array but with an associated index that labels each element.
    The index can be numerical (default) or custom labels (e.g., strings).
    While the data within a Series is mutable (can be changed), the size of the Series itself is immutable (cannot be changed after creation).

In [1]:
import pandas as pd 
import numpy as np
# Creating empty series 
ser = pd.Series() 
print("Pandas Series: ", ser) 

# simple array 
data = np.array(['P', 'G', 'M', 'C', 'A'])   
ser = pd.Series(data) 
print("Pandas Series:\n", ser)


Pandas Series:  Series([], dtype: float64)
Pandas Series:
 0    P
1    G
2    M
3    C
4    A
dtype: object


C:\Users\user1\AppData\Local\Temp\ipykernel_1792\1329178539.py:4: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  ser = pd.Series()


In [2]:
'''Creating a series from array with an index: In order to create a series by explicitly providing 
index instead of the default, we have to provide a list of elements to the index parameter with 
the same number of elements as it is an array. '''
# import pandas as pd
import pandas as pd

# import numpy as np
import numpy as np

# simple array
data = np.array(['P', 'G', 'M', 'C', 'A'])

# providing an index
ser = pd.Series(data, index=[10, 11, 12, 13, 14])
print(ser)


10    P
11    G
12    M
13    C
14    A
dtype: object


In [3]:
'''Creating a series from Lists: In order to create a series from list, 
we have to first create a list after that we can create a series from list. '''
import pandas as pd

# a simple list
list = ['P', 'G', 'M', 'C', 'A']

# create series form a list
ser = pd.Series(list)
print(ser)


0    P
1    G
2    M
3    C
4    A
dtype: object


In [4]:
'''Creating a series from Dictionary: In order to create a series from the dictionary, 
we have to first create a dictionary after that we can make a series using dictionary. 
Dictionary keys are used to construct indexes of Series. '''
import pandas as pd

# a simple dictionary
dict = {'rvce': 10,
		'for': 20,
		'MCA': 30}

# create series from dictionary
ser = pd.Series(dict)

print(ser)


rvce    10
for     20
MCA     30
dtype: int64


In [5]:
'''Creating a series from Scalar value: In order to create a series from scalar value, 
an index must be provided. The scalar value will be repeated to match the length of the index. '''
import pandas as pd

import numpy as np

# giving a scalar value with index
ser = pd.Series(10, index=[0, 1, 2, 3, 4, 5])

print(ser)


0    10
1    10
2    10
3    10
4    10
5    10
dtype: int64


In [7]:
'''Creating a series using NumPy functions : In order to create a series using numpy function, 
we can use different function of numpy like numpy.linspace(), numpy.random.radn(). '''
# import pandas and numpy
import pandas as pd
import numpy as np

# series with numpy linspace()
ser1 = pd.Series(np.linspace(3, 33, 3))
print(ser1)

# series with numpy linspace()
ser2 = pd.Series(np.linspace(1, 100, 10))
print("\n", ser2)


0     3.0
1    18.0
2    33.0
dtype: float64

 0      1.0
1     12.0
2     23.0
3     34.0
4     45.0
5     56.0
6     67.0
7     78.0
8     89.0
9    100.0
dtype: float64


In [8]:
# Creating a Series using range function
import pandas as pd
ser=pd.Series(range(10))
print(ser)

# Creating a Series using for loop and list comprehension

import pandas as pd
ser=pd.Series(range(1,20,3), index=[x for x in 'abcdefg'])
print(ser)

# Creating a Series using mathematical expressions

import pandas as pd
import numpy as np
ser=np.arange(10,15)
serobj=pd.Series(data=ser*5,index=ser)
print(serobj)


0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64
a     1
b     4
c     7
d    10
e    13
f    16
g    19
dtype: int64
10    50
11    55
12    60
13    65
14    70
dtype: int32
