In [1]:
import numpy as np
array1 = np.array([1, 3, 5, 7])
array2 = np.array([2, 4, 6, 8])
a1=np.array([[10, 20, 30], [1, 2, 3],[11, 12, 13]])
a2=np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
# using the + operator
result1 = array1 + array2
print("Using the + operator:",result1) 
print("Using the + Operator:", array1+array2)
# using the add() function
result2 = np.add(a1, a2)
print("Using the add() function:",result2) 
print(a1.ndim)

Using the + operator: [ 3  7 11 15]
Using the + Operator: [ 3  7 11 15]
Using the add() function: [[14 25 36]
 [ 8 10 12]
 [12 14 16]]
2


In [3]:
# using the - operator
result1 = array1 - array2
print("Using the - operator:",result1) 

# using the subtract() function
result2 = np.subtract(a1, a2)
print("Using the subtract() function:",result2) 

Using the - operator: [-1 -1 -1 -1]
Using the add() function: [[ 6 15 24]
 [-6 -6 -6]]


In [6]:
# using the * operator
result1 = array1 * array2
print("Using the * operator:",result1) 

# using the multiply() function
result2 = np.multiply(a1, a2)
print("Using the add() function:",result2) 

Using the - operator: [ 2 12 30 56]
Using the add() function: [[ 40 100 180]
 [  7  16  27]]


In [7]:
array1 = np.array([1, 2, 3])

# using the ** operator
result1 = array1 ** 2
print("Using the ** operator:",result1) 

# using the power() function
result2 = np.power(array1, 2)
print("Using the power() function:",result2) 

Using the ** operator: [1 4 9]
Using the power() function: [1 4 9]


In [2]:
#Statistical Methods
import numpy as np

# create a 1D array with 5 elements
array1 = np.array([1, 2, 3, 4, 5])
                                                                                                           
# calculate the median
median = np.median(array1)

print(median) 

# Output: 3.0

3.5


In [11]:
import numpy as np

# create a 2D array
array1 = np.array([[2, 4, 6], 
                   [8, 10, 12], 
                   [14, 16, 18]])

# compute median along horizontal axis 
result1 = np.median(array1, axis=1)

print("Median along horizontal axis :", result1)

# compute median along vertical axis
result2 = np.median(array1, axis=0)

print("Median along vertical axis:", result2)

# compute median of entire array
result3 = np.median(array1)

print("Median of entire array:", result3)

Median along horizontal axis : [ 4. 10. 16.]
Median along vertical axis: [ 8. 10. 12.]
Median of entire array: 10.0


In [10]:
import numpy as np

# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the mean of marks
mean_marks = np.mean(marks)

print(mean_marks)

# Output: 77.2

# create a 2D array
array1 = np.array([[1, 3], 
                 [5, 7]])

# calculate the mean of the entire array
result1 = np.mean(array1)
print("Entire Array:",result1)  # 4.0

# calculate the mean along vertical axis (axis=0)
result2 = np.mean(array1, axis=0)
print("Along Vertical Axis:",result2)  # [3. 5.]

# calculate the mean along  (axis=1)
result3 = np.mean(array1, axis=1)
print("Along Horizontal Axis :",result3)  # [2. 6.]

77.2
Entire Array: 4.0
Along Vertical Axis: [3. 5.]
Along Horizontal Axis : [2. 6.]


In [9]:
# create a 2D array
array1 = np.array([[2, 5, 9], 
                 [3, 8, 11], 
                 [4, 6, 7]])

# compute standard deviation along horizontal axis
result1 = np.std(array1, axis=1)
print("Standard deviation along horizontal axis:", result1)

# compute standard deviation along vertical axis
result2 = np.std(array1, axis=0)
print("Standard deviation  along vertical axis:", result2)

# compute standard deviation of entire array
result3 = np.std(array1)
print("Standard deviation of entire array:", result3)

Standard deviation along horizontal axis: [2.86744176 3.29983165 1.24721913]
Standard deviation  along vertical axis: [0.81649658 1.24721913 1.63299316]
Standard deviation of entire array: 2.7666443551086073


In [2]:
import numpy as np

# create an array
array1 = np.array([2,6,9,15,17,22,65,1,62])

# find the minimum value of the array
min_val = np.min(array1)

# find the maximum value of the array
max_val = np.max(array1)

# print the results
print("Minimum value:", min_val)
print("Maximum value:", max_val)

Minimum value: 1
Maximum value: 65


In [3]:
array1 = np.array([[2, 4, 6], 
                   [8, 10, 12], 
                   [14, 16, 18]])
min_val = np.min(array1)
print(min_val)


2
